---
# Playbook to create apps using templates

# - import_tasks: download_elk.yml
#   tags: [download_elk]

# This will be set_variables_shc or set_variables_sta etc.
#- import_tasks: "set_var_{{inputTag}}.yml"
#  tags: ["set_var_{{inputTag}}"]

- import_tasks: download_beats.yml
  tags: [download_beats]
