---
# This playbook is to trigger compose files

- name: Project to automate ELK (Standlone & Cluster) with Ansible
  hosts: dev
  gather_facts: no
  vars_files:
    - group_vars/common/vars_common_all.yml
    - group_vars/elk/vars_elastic_default_settings.yml
    - group_vars/elk/vars_kibana_default_settings.yml
    - group_vars/elk/vars_logstash_default_settings.yml
    - group_vars/elk/vars_elk_build_settings.yml
  roles:
    - mkouhei.include_csv
    - common
    - elk/elastic_pre_req_tasks
    - elk/kibana_build_packages
    - elk/logstash_build_packages
