---

- name: "Beats: Validate Beats suitablility for remote clients"
  import_tasks: beats_validate_clients.yml
  tags: [beats_validate_clients]

- name: "Beats: Copoy Beats installables into remote clients and then install"
  import_tasks: beats_clients_copy_install.yml
  tags: [beats_clients_copy_install]

- name: "Beats: Configure Beats in remote clients"
  import_tasks: beats_clients_configure.yml
  tags: [beats_clients_configure]
