---
- name: Gather Facts of Host where Elastic Core Stack is going to be installed
  setup:

- name: Test if the specified ELK hosts are reachable and running
  debug:
    msg: "ansible_selinux.mode={{ ansible_selinux.mode }}"
  when: ansible_selinux is defined and ansible_selinux !=False and ansible_selinux.status == 'enabled'

- name: Test to See if selinux is running. DO NOT continue if mode=enforced
  debug:
    msg: "ansible_selinux.mode={{ ansible_selinux.mode }}"
  with_items:
     - "{{beats_download_list}}"

- name: Test to relevant JVM is installed
  debug:
    msg: "ansible_selinux.mode={{ ansible_selinux.mode }}"
  with_items:
     - "{{beats_download_list}}"


- name: "Check vm.max_map_count is atleast: 262144"
  debug:
    msg: "ansible_selinux.mode={{ ansible_selinux.mode }}"
  with_items:
     - "{{beats_download_list}}"


- name: "Ulimit settings nofile to 65535 /etc/security/limits.conf"
  debug:
    msg: "ansible_selinux.mode={{ ansible_selinux.mode }}"
  with_items:
     - "{{beats_download_list}}"
